# Choose a resource for 1202@kantonspolizei-kanton-zuerich

- Anzahl Straftaten nach Tatbestand ganzer Kanton (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--06e16207a750ed44ca02.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--06e16207a750ed44ca02.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--06e16207a750ed44ca02.Rmd)
- Anzahl Straftaten nach Tatbestand und Bezirken (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--bec4afb04047d4fad66f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--bec4afb04047d4fad66f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--bec4afb04047d4fad66f.Rmd)
- Anzahl beschuldigte Personen nach Tatbestandsgruppe im ganzen Kanton (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--838b1a01346f8c29c070.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--838b1a01346f8c29c070.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--838b1a01346f8c29c070.Rmd)
- Anzahl Gewaltstraftaten nach Schweregrad und Tatbestand ganzer Kanton (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--7cc5f60db0e309b79ff5.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--7cc5f60db0e309b79ff5.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--7cc5f60db0e309b79ff5.Rmd)
- Anzahl Gewaltstraftaten nach Schweregrad und Bezirken (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--e34be2c73c9b50bdfda7.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--e34be2c73c9b50bdfda7.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--e34be2c73c9b50bdfda7.Rmd)
- Anzahl geschädigte Personen nach Tatbestandsgruppe, Alterskategorie und Geschlecht im ganzen Kanton (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--8976edd03bd6de4c5758.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--8976edd03bd6de4c5758.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--8976edd03bd6de4c5758.Rmd)
- Anzahl Straftaten nach Tatbestandsgruppe für ausgewählte Gemeinden und die Stadtkreise der Stadt Zürich (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--a7178cb14a47a0499ad7.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--a7178cb14a47a0499ad7.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--a7178cb14a47a0499ad7.Rmd)
- Anzahl Straftaten im Bereich Cyber-/Digitale Kriminalität ganzer Kanton (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--b352a17dbe33efad2b31.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--b352a17dbe33efad2b31.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--b352a17dbe33efad2b31.Rmd)
- Opfer von Gewaltstraftaten nach Geschlecht, Altersklasse, Gewaltkategorie und Qualifikation (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--babe8f4e329271789afb.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--babe8f4e329271789afb.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--babe8f4e329271789afb.Rmd)
- Beschuldigte zu Gewaltstraftaten nach Geschlecht, Altersklasse und Gewaltkategorie (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--1fae406f67d51e35910a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--1fae406f67d51e35910a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--1fae406f67d51e35910a.Rmd)
- Straftaten unter häuslicher Gewalt im Kanton Zürich (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--e5a5b36a42d8802bfc3d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--e5a5b36a42d8802bfc3d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--e5a5b36a42d8802bfc3d.Rmd)
- Straftaten unter häuslicher Gewalt nach Gemeinden (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--73ee7c4ab4bdcb950295.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--73ee7c4ab4bdcb950295.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--73ee7c4ab4bdcb950295.Rmd)
- Anzahl Einbrüche nach Gemeinden des Kantons Zürich (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--482e0105860050d4f974.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1202%40kantonspolizei-kanton-zuerich--482e0105860050d4f974.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1202%40kantonspolizei-kanton-zuerich--482e0105860050d4f974.Rmd)
