# Choose a resource for 1282@statistisches-amt-kanton-zuerich

- Ergebnisse der kommunalen Parlamentswahlen 2022 auf Ebene Kandidierende (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--66255dc2ef12d4b3a988.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--66255dc2ef12d4b3a988.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1282%40statistisches-amt-kanton-zuerich--66255dc2ef12d4b3a988.Rmd)
- Ergebnisse der kommunalen Parlamentswahlen 2022 auf Ebene Listen (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--09fbb7737e65110e4f75.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--09fbb7737e65110e4f75.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1282%40statistisches-amt-kanton-zuerich--09fbb7737e65110e4f75.Rmd)
- Ergebnisse der kommunalen Parlamentswahlen 2022 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--c77c9f6d65418c262228.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--c77c9f6d65418c262228.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1282%40statistisches-amt-kanton-zuerich--c77c9f6d65418c262228.Rmd)
- Ergebnisse der kommunalen Parlamentswahlen 2018 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--5fb2e6c0269e4055ae86.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--5fb2e6c0269e4055ae86.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1282%40statistisches-amt-kanton-zuerich--5fb2e6c0269e4055ae86.Rmd)
- Ergebnisse der kommunalen Parlamentswahlen 2018 auf Ebene Kandidierende (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--1ea23d221492058cc1e0.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--1ea23d221492058cc1e0.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1282%40statistisches-amt-kanton-zuerich--1ea23d221492058cc1e0.Rmd)
- Ergebnisse der kommunalen Parlamentswahlen 2018 auf Ebene Listen (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--796a044c8dc433dc3fc9.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--796a044c8dc433dc3fc9.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1282%40statistisches-amt-kanton-zuerich--796a044c8dc433dc3fc9.Rmd)
- Ergebnisse der kommunalen Parlamentswahlen 2026 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--7a334867fb7f716b721f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--7a334867fb7f716b721f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1282%40statistisches-amt-kanton-zuerich--7a334867fb7f716b721f.Rmd)
- Ergebnisse der kommunalen Parlamentswahlen 2026 auf Ebene Kandidierende (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--dcb197610222a6e0aa84.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--dcb197610222a6e0aa84.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1282%40statistisches-amt-kanton-zuerich--dcb197610222a6e0aa84.Rmd)
- Ergebnisse der kommunalen Parlamentswahlen 2026 auf Ebene Listen (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--8efabd1ce6c762233dfa.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1282%40statistisches-amt-kanton-zuerich--8efabd1ce6c762233dfa.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1282%40statistisches-amt-kanton-zuerich--8efabd1ce6c762233dfa.Rmd)
