# Choose a resource for 1321@personalamt-kanton-zuerich

- Personalaufwand in CHF (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--7d63dd11e5f18a48c443.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--7d63dd11e5f18a48c443.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--7d63dd11e5f18a48c443.Rmd)
- Beschäftigungsumfang nach Direktionen und Leistungsgruppen (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--88568c1ef81b680f23bc.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--88568c1ef81b680f23bc.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--88568c1ef81b680f23bc.Rmd)
- Lohnaufwand in CHF nach Direktionen und Leistungsgruppen (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--5a16385d105beefd63b5.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--5a16385d105beefd63b5.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--5a16385d105beefd63b5.Rmd)
- Beschäftigungsumfang nach Funktionsbereichen und Funktionen (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--1d98b12f1afd156230d2.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--1d98b12f1afd156230d2.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--1d98b12f1afd156230d2.Rmd)
- Anzahl Anstellungsverhältnisse nach Geschlecht und Beschäftigungsgrad nach Direktionen und Leistungsgruppen (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--9a5a963dc54b8f1a48fb.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--9a5a963dc54b8f1a48fb.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--9a5a963dc54b8f1a48fb.Rmd)
- UBS-Lohnumfragen und Lohnrunden Kanton Zürich ab 2016 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--08f8322221c1850675df.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--08f8322221c1850675df.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--08f8322221c1850675df.Rmd)
- Anzahl Ausbildungsstellen nach Ausbildungsart (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--88e75eebf5981158e7ec.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--88e75eebf5981158e7ec.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--88e75eebf5981158e7ec.Rmd)
- Anzahl Anstellungsverhältnisse nach Alter und Geschlecht (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--4487f70726da39c46ba1.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--4487f70726da39c46ba1.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--4487f70726da39c46ba1.Rmd)
- Anzahl Anstellungsverhältnisse nach Dienstjahr und Geschlecht (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--e36a49b3d0aeb0a524af.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--e36a49b3d0aeb0a524af.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--e36a49b3d0aeb0a524af.Rmd)
- Anzahl Anstellungsverhältnisse nach Lohnklasse und Geschlecht (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--beee73eea5707812e61b.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--beee73eea5707812e61b.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--beee73eea5707812e61b.Rmd)
- Anzahl Anstellungsverhältnisse nach Geschlecht und Beschäftigungsgrad ab 2020 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--9ca5d6f68434d1db26b4.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/1321%40personalamt-kanton-zuerich--9ca5d6f68434d1db26b4.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/1321%40personalamt-kanton-zuerich--9ca5d6f68434d1db26b4.Rmd)
