# Choose a resource for 2203@statistisches-amt-kanton-zuerich

- Ständeratswahl 2023 – 1. Wahlgang: Kandidierendenresultate Ebene Kanton (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--82b09df99a48a2bee056.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--82b09df99a48a2bee056.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2203%40statistisches-amt-kanton-zuerich--82b09df99a48a2bee056.Rmd)
- Ständeratswahl 2023 – 1. Wahlgang: Kandidierendenresultate Ebene Gemeinden (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--42ef64d9f4aed34a97e1.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--42ef64d9f4aed34a97e1.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2203%40statistisches-amt-kanton-zuerich--42ef64d9f4aed34a97e1.Rmd)
- Ständeratswahl 2023 – 1. Wahlgang: Wahlbeteiligung Ebene Kanton (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--a88240bf26133f3bdcb0.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--a88240bf26133f3bdcb0.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2203%40statistisches-amt-kanton-zuerich--a88240bf26133f3bdcb0.Rmd)
- Ständeratswahl 2023 – 1. Wahlgang: Wahlbeteiligung Ebene Gemeinden (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--7ab842c424cbdbd6ed79.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--7ab842c424cbdbd6ed79.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2203%40statistisches-amt-kanton-zuerich--7ab842c424cbdbd6ed79.Rmd)
- Ständeratswahl 2023 – 2. Wahlgang: Kandidierendenresultate Ebene Kanton (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--b8eb5b98fb890a8a9549.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--b8eb5b98fb890a8a9549.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2203%40statistisches-amt-kanton-zuerich--b8eb5b98fb890a8a9549.Rmd)
- Ständeratswahl 2023 – 2. Wahlgang: Kandidierendenresultate Ebene Gemeinden (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--79de08eeb7f7203c39b8.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--79de08eeb7f7203c39b8.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2203%40statistisches-amt-kanton-zuerich--79de08eeb7f7203c39b8.Rmd)
- Ständeratswahl 2023 – 2. Wahlgang: Wahlbeteiligung Ebene Kanton (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--66f4c20e0cbfa64e755d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--66f4c20e0cbfa64e755d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2203%40statistisches-amt-kanton-zuerich--66f4c20e0cbfa64e755d.Rmd)
- Ständeratswahl 2023 – 2. Wahlgang: Wahlbeteiligung Ebene Gemeinden (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--5382bb05880d3c0ffc6f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2203%40statistisches-amt-kanton-zuerich--5382bb05880d3c0ffc6f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2203%40statistisches-amt-kanton-zuerich--5382bb05880d3c0ffc6f.Rmd)
