# Choose a resource for 2382@awel-kanton-zuerich

- Daten RSD-Messkampagne 2002 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--851629833de0bd7825e7.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--851629833de0bd7825e7.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--851629833de0bd7825e7.Rmd)
- Daten RSD-Messkampagne 2003 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--8168f41d9e4e7d685da6.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--8168f41d9e4e7d685da6.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--8168f41d9e4e7d685da6.Rmd)
- Daten RSD-Messkampagne 2004 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--95c66274f5a35b5919b6.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--95c66274f5a35b5919b6.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--95c66274f5a35b5919b6.Rmd)
- Daten RSD-Messkampagne 2005 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--1f3feb4be3a644c63894.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--1f3feb4be3a644c63894.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--1f3feb4be3a644c63894.Rmd)
- Daten RSD-Messkampagne 2006 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--b58459e914bbb02fb773.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--b58459e914bbb02fb773.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--b58459e914bbb02fb773.Rmd)
- Daten RSD-Messkampagne 2007 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--d837dadb0ad96b794737.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--d837dadb0ad96b794737.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--d837dadb0ad96b794737.Rmd)
- Daten RSD-Messkampagne 2008 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--584138fadb4ba4f86694.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--584138fadb4ba4f86694.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--584138fadb4ba4f86694.Rmd)
- Daten RSD-Messkampagne 2009 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--4b99f3e067771d4d4892.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--4b99f3e067771d4d4892.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--4b99f3e067771d4d4892.Rmd)
- Daten RSD-Messkampagne 2010 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--9ecd7b950a007121792d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--9ecd7b950a007121792d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--9ecd7b950a007121792d.Rmd)
- Daten RSD-Messkampagne 2011 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--18b4f52ff99b598dac37.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--18b4f52ff99b598dac37.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--18b4f52ff99b598dac37.Rmd)
- Daten RSD-Messkampagne 2012 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--3ee95a0166ddcfc047e1.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--3ee95a0166ddcfc047e1.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--3ee95a0166ddcfc047e1.Rmd)
- Daten RSD-Messkampagne 2013 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--61e34781a59d4e98a2fc.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--61e34781a59d4e98a2fc.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--61e34781a59d4e98a2fc.Rmd)
- Daten RSD-Messkampagne 2014 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--9a86ccfe46feddcafca8.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--9a86ccfe46feddcafca8.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--9a86ccfe46feddcafca8.Rmd)
- Daten RSD-Messkampagne 2015 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--3ad7dc882387ffc3df5a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--3ad7dc882387ffc3df5a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--3ad7dc882387ffc3df5a.Rmd)
- Daten RSD-Messkampagne 2016 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--4cc54de65980814b0155.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--4cc54de65980814b0155.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--4cc54de65980814b0155.Rmd)
- Daten RSD-Messkampagne 2017 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--358e55d4f48b67f5e24b.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--358e55d4f48b67f5e24b.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--358e55d4f48b67f5e24b.Rmd)
- Daten RSD-Messkampagne 2018 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--600ad1fa914449da991f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--600ad1fa914449da991f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--600ad1fa914449da991f.Rmd)
- Daten RSD-Messkampagne 2019 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--ad4348d59891098130df.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--ad4348d59891098130df.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--ad4348d59891098130df.Rmd)
- Daten RSD-Messkampagne 2020 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--85f08e8801c889a4c419.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--85f08e8801c889a4c419.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--85f08e8801c889a4c419.Rmd)
- Daten RSD-Messkampagne 2021 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--d960b2e60c7eeb2af6e1.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--d960b2e60c7eeb2af6e1.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--d960b2e60c7eeb2af6e1.Rmd)
- Daten RSD-Messkampagne 2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--55d0f3fea2d1795fc7b5.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--55d0f3fea2d1795fc7b5.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--55d0f3fea2d1795fc7b5.Rmd)
- Daten RSD-Messkampagne 2025 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--fdec3e0247056b6ae85e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2382%40awel-kanton-zuerich--fdec3e0247056b6ae85e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2382%40awel-kanton-zuerich--fdec3e0247056b6ae85e.Rmd)
