# Choose a resource for 2383@awel-kanton-zuerich

- Messdaten Luftschadstoffe und Meteorologie Kloten Feld 2020 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--bcbcfdb43978b8556837.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--bcbcfdb43978b8556837.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2383%40awel-kanton-zuerich--bcbcfdb43978b8556837.Rmd)
- Messdaten Luftschadstoffe und Meteorologie Kloten Feld 2021 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--7a30d08464cf70cbc728.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--7a30d08464cf70cbc728.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2383%40awel-kanton-zuerich--7a30d08464cf70cbc728.Rmd)
- Messdaten Luftschadstoffe und Meteorologie Kloten Feld 2022 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--a701a62a878065b65517.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--a701a62a878065b65517.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2383%40awel-kanton-zuerich--a701a62a878065b65517.Rmd)
- Messdaten Luftschadstoffe und Meteorologie Kloten Feld 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--5bb2231f7e7b35024e19.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--5bb2231f7e7b35024e19.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2383%40awel-kanton-zuerich--5bb2231f7e7b35024e19.Rmd)
- Messdaten Aerosol Anzahl-Grössenverteilungen Kloten Feld 2020 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--dde57ae2e95c8b0aa886.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--dde57ae2e95c8b0aa886.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2383%40awel-kanton-zuerich--dde57ae2e95c8b0aa886.Rmd)
- Messdaten Aerosol Anzahl-Grössenverteilungen Kloten Feld 2021 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--a76c33f5c46835e80e1c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--a76c33f5c46835e80e1c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2383%40awel-kanton-zuerich--a76c33f5c46835e80e1c.Rmd)
- Messdaten Aerosol Anzahl-Grössenverteilungen Kloten Feld 2022 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--94ddf6b6d2d33582ee43.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--94ddf6b6d2d33582ee43.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2383%40awel-kanton-zuerich--94ddf6b6d2d33582ee43.Rmd)
- Messdaten Aerosol Anzahl-Grössenverteilungen Kloten Feld 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--0c164c491cdc1bc0bcb4.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/2383%40awel-kanton-zuerich--0c164c491cdc1bc0bcb4.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/2383%40awel-kanton-zuerich--0c164c491cdc1bc0bcb4.Rmd)
