# Choose a resource for 3162@statistisches-amt-kanton-zuerich

- Abklärungen Lernprogramm PoG® (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--1760790300300bebb868.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--1760790300300bebb868.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--1760790300300bebb868.Rmd)
- Programmabschlüsse Lernprogramm PoG® (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--72a0c19d7745c8c6755c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--72a0c19d7745c8c6755c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--72a0c19d7745c8c6755c.Rmd)
- Häusliche Gewaltverfahren der Statthalterämter (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--c53fa6f05c1a0cfcd5b0.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--c53fa6f05c1a0cfcd5b0.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--c53fa6f05c1a0cfcd5b0.Rmd)
- Ansprachen von Gefährdenden (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--94429ee10f4c6e85e189.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--94429ee10f4c6e85e189.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--94429ee10f4c6e85e189.Rmd)
- Gewaltschutzverfahren vor den Bezirksgerichten (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--34463d2838db57b40be2.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--34463d2838db57b40be2.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--34463d2838db57b40be2.Rmd)
- Antragsarten bei Gewaltschutzverfahren vor den Bezirksgerichten (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--e94022b7951743cf6b9d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--e94022b7951743cf6b9d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--e94022b7951743cf6b9d.Rmd)
- Frauenhäuser: Belegung und Betreuungszahlen (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--e2f47ff1d86b3319eb5f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--e2f47ff1d86b3319eb5f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--e2f47ff1d86b3319eb5f.Rmd)
- Polizeieinsätze und Gewaltschutzmassnahmen (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--b02b6ea874ff6e29edb5.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--b02b6ea874ff6e29edb5.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--b02b6ea874ff6e29edb5.Rmd)
- Erledigungen Staatsanwaltschaft (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--38045abab851e56f56ee.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--38045abab851e56f56ee.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--38045abab851e56f56ee.Rmd)
- Schutzunterkünfte für Minderjährige: Belegung und Beratungszahlen (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--4a69d946c3317efc960d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--4a69d946c3317efc960d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--4a69d946c3317efc960d.Rmd)
- Aufsuchender Dienst Forensic Nurses (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--6649e19efdac8e3ddc47.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--6649e19efdac8e3ddc47.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--6649e19efdac8e3ddc47.Rmd)
- Opferhilfe: Beratungszahlen (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--9637ef2e13758d77d52a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/3162%40statistisches-amt-kanton-zuerich--9637ef2e13758d77d52a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/3162%40statistisches-amt-kanton-zuerich--9637ef2e13758d77d52a.Rmd)
