# Choose a resource for 563@awel-kanton-zuerich

- LoRa-Sensor-Messwerte 2020/03 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--71beceb423224e9a1322.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--71beceb423224e9a1322.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--71beceb423224e9a1322.Rmd)
- LoRa-Sensor-Messwerte 2020/02 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--0af1b3c04b80428d0c40.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--0af1b3c04b80428d0c40.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--0af1b3c04b80428d0c40.Rmd)
- LoRa-Sensor-Messwerte 2020/01 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5408c406226cb5581d6d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5408c406226cb5581d6d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--5408c406226cb5581d6d.Rmd)
- LoRa-Sensor-Messwerte 2019/12 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--4b0721d53c03ffa4a1ce.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--4b0721d53c03ffa4a1ce.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--4b0721d53c03ffa4a1ce.Rmd)
- LoRa-Sensor-Messwerte 2019/11 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--50139a2e43b523a30256.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--50139a2e43b523a30256.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--50139a2e43b523a30256.Rmd)
- LoRa-Sensor-Messwerte 2019/10 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--e86ff4c9ea0da1268517.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--e86ff4c9ea0da1268517.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--e86ff4c9ea0da1268517.Rmd)
- LoRa-Sensor-Messwerte 2019/09 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--8c37a405dd9ba27af138.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--8c37a405dd9ba27af138.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--8c37a405dd9ba27af138.Rmd)
- LoRa-Sensor-Messwerte 2019/08 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--6ba7082a3c88ccf3fd76.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--6ba7082a3c88ccf3fd76.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--6ba7082a3c88ccf3fd76.Rmd)
- LoRa-Sensor-Messwerte 2019/07 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ba7346cd7e094ae7d4bd.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ba7346cd7e094ae7d4bd.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--ba7346cd7e094ae7d4bd.Rmd)
- LoRa-Sensor-Messwerte 2019/06 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5ab6c2bb7c871b96f313.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5ab6c2bb7c871b96f313.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--5ab6c2bb7c871b96f313.Rmd)
- LoRa-Sensor-Messwerte 2019/05 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--28ecc3aebf9b483ac1f2.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--28ecc3aebf9b483ac1f2.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--28ecc3aebf9b483ac1f2.Rmd)
- LoRa-Sensor-Messwerte 2020/04 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--a1271aedce43acc0cb40.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--a1271aedce43acc0cb40.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--a1271aedce43acc0cb40.Rmd)
- LoRa-Sensor-Messwerte 2020/05 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--6f0ef1ffa85e1a2a23e8.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--6f0ef1ffa85e1a2a23e8.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--6f0ef1ffa85e1a2a23e8.Rmd)
- LoRa-Sensor-Messwerte 2020/06 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--28f48981d0513018056e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--28f48981d0513018056e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--28f48981d0513018056e.Rmd)
- LoRa-Sensor-Messwerte 2020/07 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--7948b7abb383f4c47f8c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--7948b7abb383f4c47f8c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--7948b7abb383f4c47f8c.Rmd)
- LoRa-Sensor-Messwerte 2020/08 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b4a0ee4b2f553219d2a8.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b4a0ee4b2f553219d2a8.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--b4a0ee4b2f553219d2a8.Rmd)
- LoRa-Sensor-Messwerte 2020/09 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--24ef02dd0ef92450e0e4.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--24ef02dd0ef92450e0e4.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--24ef02dd0ef92450e0e4.Rmd)
- LoRa-Sensor-Messwerte 2020/10 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--84f49afa19091c7b3551.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--84f49afa19091c7b3551.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--84f49afa19091c7b3551.Rmd)
- LoRa-Sensor-Messwerte 2020/11 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--a26373da49b4a09b0c28.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--a26373da49b4a09b0c28.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--a26373da49b4a09b0c28.Rmd)
- LoRa-Sensor-Messwerte 2020/12 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--d5f0d4810d441fd4fb2e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--d5f0d4810d441fd4fb2e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--d5f0d4810d441fd4fb2e.Rmd)
- LoRa-Sensor-Messwerte 2021/01 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--69bb3c75b6c12cd65a60.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--69bb3c75b6c12cd65a60.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--69bb3c75b6c12cd65a60.Rmd)
- LoRa-Sensor-Messwerte 2021/02 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--6a59a7cc5cd19b9b4986.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--6a59a7cc5cd19b9b4986.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--6a59a7cc5cd19b9b4986.Rmd)
- LoRa-Sensor-Messwerte 2021/03 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--7140d2087c1a5ca5536b.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--7140d2087c1a5ca5536b.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--7140d2087c1a5ca5536b.Rmd)
- LoRa-Sensor-Messwerte 2021/04 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--05ebdd0288e92628788c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--05ebdd0288e92628788c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--05ebdd0288e92628788c.Rmd)
- LoRa-Sensor-Messwerte 2021/05 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--734b14e7bde34157ad3a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--734b14e7bde34157ad3a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--734b14e7bde34157ad3a.Rmd)
- LoRa-Sensor-Messwerte 2021/06 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--6a26d85c020ef3283dbe.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--6a26d85c020ef3283dbe.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--6a26d85c020ef3283dbe.Rmd)
- LoRa-Sensor-Messwerte 2021/07 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ccf667ff34ddd9ca1d01.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ccf667ff34ddd9ca1d01.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--ccf667ff34ddd9ca1d01.Rmd)
- LoRa-Sensor-Messwerte 2021/08 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--f15eae690a6978c5797d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--f15eae690a6978c5797d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--f15eae690a6978c5797d.Rmd)
- LoRa-Sensor-Messwerte 2021/09 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--d14ead2d7ad17b2ff18c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--d14ead2d7ad17b2ff18c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--d14ead2d7ad17b2ff18c.Rmd)
- LoRa-Sensor-Messwerte 2021/10 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--64039cb7fa6e7d794f45.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--64039cb7fa6e7d794f45.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--64039cb7fa6e7d794f45.Rmd)
- LoRa-Sensor-Messwerte 2021/11 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--7efc16294b08d816d37b.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--7efc16294b08d816d37b.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--7efc16294b08d816d37b.Rmd)
- LoRa-Sensor-Messwerte 2021/12 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--0c79c11a4d2579dbb658.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--0c79c11a4d2579dbb658.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--0c79c11a4d2579dbb658.Rmd)
- LoRa-Sensor-Messwerte 2022/01 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--85e49f09ebdd1722d547.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--85e49f09ebdd1722d547.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--85e49f09ebdd1722d547.Rmd)
- LoRa-Sensor-Messwerte 2022/02 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--acad7deb55474bcbeb92.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--acad7deb55474bcbeb92.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--acad7deb55474bcbeb92.Rmd)
- LoRa-Sensor-Messwerte 2022/03 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--9eaf40a49d4f47f3dee6.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--9eaf40a49d4f47f3dee6.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--9eaf40a49d4f47f3dee6.Rmd)
- LoRa-Sensor-Messwerte 2022/04 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--15a0a0eb1f743d1f212c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--15a0a0eb1f743d1f212c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--15a0a0eb1f743d1f212c.Rmd)
- LoRa-Sensor-Messwerte 2022/05 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ff237d01cf496f1bfef2.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ff237d01cf496f1bfef2.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--ff237d01cf496f1bfef2.Rmd)
- LoRa-Sensor-Messwerte 2022/06 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--cbd1622c354a89597be7.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--cbd1622c354a89597be7.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--cbd1622c354a89597be7.Rmd)
- LoRa-Sensor-Messwerte 2022/07 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--62d4a83cecc8f2c5490c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--62d4a83cecc8f2c5490c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--62d4a83cecc8f2c5490c.Rmd)
- LoRa-Sensor-Messwerte 2022/08 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5f5bd46311c84cd289dc.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5f5bd46311c84cd289dc.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--5f5bd46311c84cd289dc.Rmd)
- LoRa-Sensor-Messwerte 2019/04 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--87fb64b36ee71be6960b.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--87fb64b36ee71be6960b.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--87fb64b36ee71be6960b.Rmd)
- LoRa-Sensor-Messwerte 2022/09 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5395b34ebdb74df8f760.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5395b34ebdb74df8f760.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--5395b34ebdb74df8f760.Rmd)
- LoRa-Sensor-Messwerte 2022/10 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--fbdd5af2de85001b38e1.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--fbdd5af2de85001b38e1.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--fbdd5af2de85001b38e1.Rmd)
- LoRa-Sensor-Messwerte 2022/11 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--a729f7f5ea22ee4f9b7d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--a729f7f5ea22ee4f9b7d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--a729f7f5ea22ee4f9b7d.Rmd)
- LoRa-Sensor-Messwerte 2022/12 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--59160e65ff3a5134f809.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--59160e65ff3a5134f809.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--59160e65ff3a5134f809.Rmd)
- LoRa-Sensor-Messwerte 2023/02 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--2206234dfcd55b3e55ca.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--2206234dfcd55b3e55ca.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--2206234dfcd55b3e55ca.Rmd)
- LoRa-Sensor-Messwerte 2023/01 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ffc3aad2d2fd17f181c6.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ffc3aad2d2fd17f181c6.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--ffc3aad2d2fd17f181c6.Rmd)
- LoRa-Sensor-Messwerte 2023/03 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--3f555a21a4cbdee9be0f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--3f555a21a4cbdee9be0f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--3f555a21a4cbdee9be0f.Rmd)
- LoRa-Sensor-Messwerte 2023/04 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--481c4053b10f9c36dd99.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--481c4053b10f9c36dd99.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--481c4053b10f9c36dd99.Rmd)
- LoRa-Sensor-Messwerte 2023/05 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--da5b5d66723ca9d68027.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--da5b5d66723ca9d68027.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--da5b5d66723ca9d68027.Rmd)
- LoRa-Sensor-Messwerte 2023/06 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--818c5aaef016cafad0a1.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--818c5aaef016cafad0a1.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--818c5aaef016cafad0a1.Rmd)
- LoRa-Sensor-Messwerte 2023/07 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--f61eeb756ba4b35c6c7f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--f61eeb756ba4b35c6c7f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--f61eeb756ba4b35c6c7f.Rmd)
- LoRa-Sensor-Messwerte 2023/08 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b89ffd5aabe7d57bc815.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b89ffd5aabe7d57bc815.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--b89ffd5aabe7d57bc815.Rmd)
- LoRa-Sensor-Messwerte 2023/09 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b40d9fb9aa301154cbe8.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b40d9fb9aa301154cbe8.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--b40d9fb9aa301154cbe8.Rmd)
- LoRa-Sensor-Messwerte 2023/10 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--81ce461024dba4be1fcf.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--81ce461024dba4be1fcf.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--81ce461024dba4be1fcf.Rmd)
- LoRa-Sensor-Messwerte 2023/11 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--98c2eb10aee95cf9ae48.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--98c2eb10aee95cf9ae48.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--98c2eb10aee95cf9ae48.Rmd)
- LoRa-Sensor-Messwerte 2023/12 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ea6f06390a0c2570f83b.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ea6f06390a0c2570f83b.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--ea6f06390a0c2570f83b.Rmd)
- LoRa-Sensor-Messwerte 2024/01 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--99af40376c37bdf515af.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--99af40376c37bdf515af.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--99af40376c37bdf515af.Rmd)
- LoRa-Sensor-Messwerte 2024/02 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--81bf059acb5f805d65af.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--81bf059acb5f805d65af.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--81bf059acb5f805d65af.Rmd)
- LoRa-Sensor-Messwerte 2024/03 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--193baa561ef88bfe2e2e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--193baa561ef88bfe2e2e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--193baa561ef88bfe2e2e.Rmd)
- LoRa-Sensor-Messwerte 2024/04 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--fe7e38a565477e4b7798.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--fe7e38a565477e4b7798.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--fe7e38a565477e4b7798.Rmd)
- LoRa-Sensor-Messwerte 2024/05 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--f3527ae4d1fd17101e91.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--f3527ae4d1fd17101e91.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--f3527ae4d1fd17101e91.Rmd)
- LoRa-Sensor-Messwerte 2024/06 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5146108802c219e6e91e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5146108802c219e6e91e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--5146108802c219e6e91e.Rmd)
- LoRa-Sensor-Messwerte 2024/07 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--14a4c36965b0fdd4ad19.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--14a4c36965b0fdd4ad19.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--14a4c36965b0fdd4ad19.Rmd)
- LoRa-Sensor-Messwerte 2024/08 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--f3f425a77c519b7761b1.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--f3f425a77c519b7761b1.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--f3f425a77c519b7761b1.Rmd)
- LoRa-Sensor-Messwerte 2024/09 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--2f2b6b6206a27d53edfc.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--2f2b6b6206a27d53edfc.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--2f2b6b6206a27d53edfc.Rmd)
- LoRa-Sensor-Messwerte 2024/10 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--87a34552f59279fe0cb6.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--87a34552f59279fe0cb6.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--87a34552f59279fe0cb6.Rmd)
- LoRa-Sensor-Messwerte 2024/11 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--3d86544d6a34ccb8bf03.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--3d86544d6a34ccb8bf03.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--3d86544d6a34ccb8bf03.Rmd)
- LoRa-Sensor-Messwerte 2024/12 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b9ab92f23c8de5c1c95a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b9ab92f23c8de5c1c95a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--b9ab92f23c8de5c1c95a.Rmd)
- LoRa-Sensor-Messwerte 2025/01 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b313b39c8ac54ebdf7cb.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b313b39c8ac54ebdf7cb.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--b313b39c8ac54ebdf7cb.Rmd)
- LoRa-Sensor-Messwerte 2025/02 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--d6fb35c0e773582385d7.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--d6fb35c0e773582385d7.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--d6fb35c0e773582385d7.Rmd)
- LoRa-Sensor-Messwerte 2025/03 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b7791735c0fbd6da5075.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b7791735c0fbd6da5075.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--b7791735c0fbd6da5075.Rmd)
- LoRa-Sensor-Messwerte 2025/04 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--db1be5b1d4e160adea8c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--db1be5b1d4e160adea8c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--db1be5b1d4e160adea8c.Rmd)
- LoRa-Sensor-Messwerte 2025/05 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--92152a835fd5bc5948ad.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--92152a835fd5bc5948ad.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--92152a835fd5bc5948ad.Rmd)
- LoRa-Sensor-Messwerte 2025/06 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--85e74613978b7d5c483f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--85e74613978b7d5c483f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--85e74613978b7d5c483f.Rmd)
- LoRa-Sensor-Messwerte 2025/07 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--da2029eff0db674f1d00.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--da2029eff0db674f1d00.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--da2029eff0db674f1d00.Rmd)
- LoRa-Sensor-Messwerte 2025/08 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--e12e6ffd167048af8065.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--e12e6ffd167048af8065.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--e12e6ffd167048af8065.Rmd)
- LoRa-Sensor-Messwerte 2025/09 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--0a6ba6c330c5e3f82564.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--0a6ba6c330c5e3f82564.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--0a6ba6c330c5e3f82564.Rmd)
- LoRa-Sensor-Messwerte 2025/10 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--7b2d6464b119db02daba.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--7b2d6464b119db02daba.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--7b2d6464b119db02daba.Rmd)
- LoRa-Sensor-Messwerte 2025/11 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ea9ff2eca4e82f251935.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--ea9ff2eca4e82f251935.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--ea9ff2eca4e82f251935.Rmd)
- LoRa-Sensor-Messwerte 2025/12 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--00c392499ed8856ca2a6.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--00c392499ed8856ca2a6.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--00c392499ed8856ca2a6.Rmd)
- LoRa-Sensor-Messwerte 2026/01 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--e633d38185198d2c5634.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--e633d38185198d2c5634.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--e633d38185198d2c5634.Rmd)
- LoRa-Sensor-Messwerte 2026/02 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--233d7ca3c7996bdbb09b.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--233d7ca3c7996bdbb09b.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--233d7ca3c7996bdbb09b.Rmd)
- LoRa-Sensor-Messwerte 2026/03 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--07b11ff54f10f394d100.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--07b11ff54f10f394d100.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--07b11ff54f10f394d100.Rmd)
- LoRa-Sensor-Messwerte 2026/04 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--2d7d221bc6a11ae059e3.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--2d7d221bc6a11ae059e3.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--2d7d221bc6a11ae059e3.Rmd)
- LoRa-Sensor-Messwerte 2026/05 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--e041feaf0688b02278ed.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--e041feaf0688b02278ed.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--e041feaf0688b02278ed.Rmd)
- LoRa-Sensor-Messwerte 2026/06 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b98e3ab75f2444993c9b.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--b98e3ab75f2444993c9b.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--b98e3ab75f2444993c9b.Rmd)
- LoRa-Sensor-Messwerte 2026/07 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--393ae03e7f9126139288.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--393ae03e7f9126139288.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--393ae03e7f9126139288.Rmd)
- LoRa-Sensor-Messwerte 2026/08 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5fce1be90707d080b75f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--5fce1be90707d080b75f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--5fce1be90707d080b75f.Rmd)
- LoRa-Sensor-Messwerte 2026/09 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--1cff23af346963e42d44.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/563%40awel-kanton-zuerich--1cff23af346963e42d44.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/563%40awel-kanton-zuerich--1cff23af346963e42d44.Rmd)
