# Choose a resource for 671@gesundheitsdirektion-kanton-zuerich

- COVID&#95;19 Fallzahlen Kanton Zürich nach Alter und Geschlecht bis 03.01.2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--c03c860cee0d69d11078.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--c03c860cee0d69d11078.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/671%40gesundheitsdirektion-kanton-zuerich--c03c860cee0d69d11078.Rmd)
- COVID&#95;19 Fallzahlen Kanton Zürich pro Tag ab 27.02.2020 bis 03.01.2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--e413616e3a4b4340e599.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--e413616e3a4b4340e599.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/671%40gesundheitsdirektion-kanton-zuerich--e413616e3a4b4340e599.Rmd)
- COVID&#95;19 Fallzahlen Kanton Zürich nach Bezirk und Kalenderwoche ab 24.02.2020 bis 03.01.2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--79d08266e5fdbe9df638.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--79d08266e5fdbe9df638.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/671%40gesundheitsdirektion-kanton-zuerich--79d08266e5fdbe9df638.Rmd)
- COVID&#95;19 Verteilung der Fälle im Kanton Zürich nach Altersklasse, Geschlecht und Kalenderwoche ab 24.02.2020 bis 03.01.2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--32d61880e4ab0f506ed2.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--32d61880e4ab0f506ed2.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/671%40gesundheitsdirektion-kanton-zuerich--32d61880e4ab0f506ed2.Rmd)
- COVID&#95;19 Verteilung der Fälle im Kanton Zürich nach Postleitzahl ab 09.07.2020 bis 03.01.2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--a4b88a2fca48540241fb.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--a4b88a2fca48540241fb.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/671%40gesundheitsdirektion-kanton-zuerich--a4b88a2fca48540241fb.Rmd)
- COVID&#95;19 Anteil der positiven SARS-CoV-2 Tests im Kanton Zürich nach Kalenderwoche ab 25.05.2020  bis 03.01.2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--427132679d3d2e6e53b6.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--427132679d3d2e6e53b6.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/671%40gesundheitsdirektion-kanton-zuerich--427132679d3d2e6e53b6.Rmd)
- COVID&#95;19 Anteil der positiven SARS-CoV-2 Tests im Kanton Zürich nach Altersklasse und Kalenderwoche ab 25.05.2020 bis 03.01.2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--ee50b2ad512ff1f8d40f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--ee50b2ad512ff1f8d40f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/671%40gesundheitsdirektion-kanton-zuerich--ee50b2ad512ff1f8d40f.Rmd)
- COVID&#95;19 Anteil der positiven SARS-CoV-2 Tests im Kanton Zürich bei Kindern und Jugendlichen nach Altersklasse und Kalenderwoche ab 25.05.2020 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--a241e54cdce4286d2c8f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--a241e54cdce4286d2c8f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/671%40gesundheitsdirektion-kanton-zuerich--a241e54cdce4286d2c8f.Rmd)
- COVID&#95;19 PCR-Tests und besorgniserregende Virusmutationen im Kanton Zürich (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--f97c6267a68e3ef41973.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/671%40gesundheitsdirektion-kanton-zuerich--f97c6267a68e3ef41973.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/671%40gesundheitsdirektion-kanton-zuerich--f97c6267a68e3ef41973.Rmd)
