# Choose a resource for 690@statistisches-amt-kanton-zuerich

- Panaschierstatistik Erneuerungswahl Kantonsrat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--7d1bc1af05f70df3f078.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--7d1bc1af05f70df3f078.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--7d1bc1af05f70df3f078.Rmd)
- Gemeindeinformationen Erneuerungswahl Kantonsrat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--3711fdbf5d4e133cc741.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--3711fdbf5d4e133cc741.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--3711fdbf5d4e133cc741.Rmd)
- Panaschierstatistik Erneuerungswahl Kantonsrat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--f94719193015d20644ce.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--f94719193015d20644ce.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--f94719193015d20644ce.Rmd)
- Gemeindeinformationen Erneuerungswahl Kantonsrat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--c571237cf00629ef60e1.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--c571237cf00629ef60e1.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--c571237cf00629ef60e1.Rmd)
- Panaschierstatistik Erneuerungswahl Kantonsrat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--7e3832030dd63b373c9b.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--7e3832030dd63b373c9b.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--7e3832030dd63b373c9b.Rmd)
- Gemeindeinformationen Erneuerungswahl Kantonsrat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--998e938d0a9ccfeefe85.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--998e938d0a9ccfeefe85.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--998e938d0a9ccfeefe85.Rmd)
- Panaschierstatistik Erneuerungswahl Kantonsrat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--dfdf013fafe0025a8539.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--dfdf013fafe0025a8539.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--dfdf013fafe0025a8539.Rmd)
- Gemeindeinformationen Erneuerungswahl Kantonsrat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--f51d5a3ad944cbbeffba.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--f51d5a3ad944cbbeffba.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--f51d5a3ad944cbbeffba.Rmd)
- Kandidierende Erneuerungswahl Kantonsrat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--40f61e8b1965731195fb.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--40f61e8b1965731195fb.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--40f61e8b1965731195fb.Rmd)
- Kandidierende Erneuerungswahl Kantonsrat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--da555d54df1e791a277f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--da555d54df1e791a277f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--da555d54df1e791a277f.Rmd)
- Kandidierende Erneuerungswahl Kantonsrat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--23768964534288245441.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--23768964534288245441.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--23768964534288245441.Rmd)
- Kandidierende Erneuerungswahl Kantonsrat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--2abce6c3fe44bde4155a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--2abce6c3fe44bde4155a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--2abce6c3fe44bde4155a.Rmd)
- Panaschierstatistik Erneuerungswahl Kantonsrat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--fd3e57c7729ea6dc4341.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--fd3e57c7729ea6dc4341.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--fd3e57c7729ea6dc4341.Rmd)
- Kandidierende Erneuerungswahl Kantonsrat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--e83a56305578db8ce88c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--e83a56305578db8ce88c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--e83a56305578db8ce88c.Rmd)
- Gemeindeinformationen Erneuerungswahl Kantonsrat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--7ee352291a3225c1aad7.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--7ee352291a3225c1aad7.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--7ee352291a3225c1aad7.Rmd)
- Zuordnungstabelle Listen – Parteien (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--6b7bb8dbf62e2645a864.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--6b7bb8dbf62e2645a864.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--6b7bb8dbf62e2645a864.Rmd)
- Parteiresultate Erneuerungswahl Kantonsrat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--510efd4b25add552ce54.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--510efd4b25add552ce54.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--510efd4b25add552ce54.Rmd)
- Listenresultate Erneuerungswahl Kantonsrat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--1be2e6c4cf3377837c5a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--1be2e6c4cf3377837c5a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--1be2e6c4cf3377837c5a.Rmd)
- Parteiresultate Erneuerungswahl Kantonsrat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--2cc2704f933b61a75515.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--2cc2704f933b61a75515.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--2cc2704f933b61a75515.Rmd)
- Listenresultate Erneuerungswahl Kantonsrat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--b97ed2046014566e2ecf.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--b97ed2046014566e2ecf.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--b97ed2046014566e2ecf.Rmd)
- Parteiresultate Erneuerungswahl Kantonsrat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--94dc10c68a89391d4f2f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--94dc10c68a89391d4f2f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--94dc10c68a89391d4f2f.Rmd)
- Listenresultate Erneuerungswahl Kantonsrat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--2277087c92bb391929db.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--2277087c92bb391929db.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--2277087c92bb391929db.Rmd)
- Parteiresultate Erneuerungswahl Kantonsrat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--b139a818f45c4622fb50.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--b139a818f45c4622fb50.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--b139a818f45c4622fb50.Rmd)
- Listenresultate Erneuerungswahl Kantonsrat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--62dd2ea9be9c2f7d11d5.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--62dd2ea9be9c2f7d11d5.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--62dd2ea9be9c2f7d11d5.Rmd)
- Parteiresultate Erneuerungswahl Kantonsrat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--90f01cfc5b3d10e25015.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--90f01cfc5b3d10e25015.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--90f01cfc5b3d10e25015.Rmd)
- Listenresultate Erneuerungswahl Kantonsrat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--6edfe2e311b326b7c5cd.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/690%40statistisches-amt-kanton-zuerich--6edfe2e311b326b7c5cd.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/690%40statistisches-amt-kanton-zuerich--6edfe2e311b326b7c5cd.Rmd)
