# Choose a resource for 693@statistisches-amt-kanton-zuerich

- Panaschierstatistik Erneuerungswahl Nationalrat 2007 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--3ff657ebcaf553e04b2a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--3ff657ebcaf553e04b2a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--3ff657ebcaf553e04b2a.Rmd)
- Gemeindeinformationen Erneuerungswahl Nationalrat 2007 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--1bd50d335ff404940077.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--1bd50d335ff404940077.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--1bd50d335ff404940077.Rmd)
- Listenverbindungen Erneuerungswahl Nationalrat 2007 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--26af213dc7b3fb433243.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--26af213dc7b3fb433243.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--26af213dc7b3fb433243.Rmd)
- Panaschierstatistik Erneuerungswahl Nationalrat 2011 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--ebc11e9c4e9bad1500a8.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--ebc11e9c4e9bad1500a8.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--ebc11e9c4e9bad1500a8.Rmd)
- Gemeindeinformationen Erneuerungswahl Nationalrat 2011 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--63f3d887d03975953bb1.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--63f3d887d03975953bb1.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--63f3d887d03975953bb1.Rmd)
- Listenverbindungen Erneuerungswahl Nationalrat 2011 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--9ac8cbfec498f2b2dc35.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--9ac8cbfec498f2b2dc35.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--9ac8cbfec498f2b2dc35.Rmd)
- Panaschierstatistik Erneuerungswahl Nationalrat 2015 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--94c50d31ec13b92ad10c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--94c50d31ec13b92ad10c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--94c50d31ec13b92ad10c.Rmd)
- Gemeindeinformationen Erneuerungswahl Nationalrat 2015 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--12346261eabb53d04e3a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--12346261eabb53d04e3a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--12346261eabb53d04e3a.Rmd)
- Listenverbindungen Erneuerungswahl Nationalrat 2015 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--e9059d7fe661d1023fb1.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--e9059d7fe661d1023fb1.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--e9059d7fe661d1023fb1.Rmd)
- Panaschierstatistik Erneuerungswahl Nationalrat 2019 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--af3c8c005902b52d571a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--af3c8c005902b52d571a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--af3c8c005902b52d571a.Rmd)
- Gemeindeinformationen Erneuerungswahl Nationalrat 2019 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--c3e150f5e9e5b7ed9c9e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--c3e150f5e9e5b7ed9c9e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--c3e150f5e9e5b7ed9c9e.Rmd)
- Listenverbindungen Erneuerungswahl Nationalrat 2019 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--57f1bf91c03f92be380c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--57f1bf91c03f92be380c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--57f1bf91c03f92be380c.Rmd)
- Kandidierende Erneuerungswahl Nationalrat 2007 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--0a67a061d3fd512ca964.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--0a67a061d3fd512ca964.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--0a67a061d3fd512ca964.Rmd)
- Kandidierende Erneuerungswahl Nationalrat 2011 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--a21f6ea7330d13ef08ed.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--a21f6ea7330d13ef08ed.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--a21f6ea7330d13ef08ed.Rmd)
- Kandidierende Erneuerungswahl Nationalrat 2015 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--71bc89abf3c051df7f3d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--71bc89abf3c051df7f3d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--71bc89abf3c051df7f3d.Rmd)
- Kandidierende Erneuerungswahl Nationalrat 2019 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--9557b80374ac3ac65af0.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--9557b80374ac3ac65af0.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--9557b80374ac3ac65af0.Rmd)
- Listenverbindungen Erneuerungswahl Nationalrat 2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--71fd2ec9522beced459a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--71fd2ec9522beced459a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--71fd2ec9522beced459a.Rmd)
- Kandidierende Erneuerungswahl Nationalrat 2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--7c6702443746f6a6ef20.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--7c6702443746f6a6ef20.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--7c6702443746f6a6ef20.Rmd)
- Gemeindeinformationen Erneuerungswahl Nationalrat 2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--ff6b152d3847da22600a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--ff6b152d3847da22600a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--ff6b152d3847da22600a.Rmd)
- Panaschierstatistik Erneuerungswahl Nationalrat 2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--58a34003cea4f267129f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--58a34003cea4f267129f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--58a34003cea4f267129f.Rmd)
- Zuordnungstabelle Listen – Parteien (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--38dcfb900516739d0bb4.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--38dcfb900516739d0bb4.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--38dcfb900516739d0bb4.Rmd)
- Parteiresultate Erneuerungswahl Nationalrat 2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--c168007b6e6095573546.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--c168007b6e6095573546.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--c168007b6e6095573546.Rmd)
- Listenresultate Erneuerungswahl Nationalrat 2023 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--4dea468920622eec30b9.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--4dea468920622eec30b9.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--4dea468920622eec30b9.Rmd)
- Parteiresultate Erneuerungswahl Nationalrat 2019 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--458b9403b47b7a760483.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--458b9403b47b7a760483.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--458b9403b47b7a760483.Rmd)
- Listenresultate Erneuerungswahl Nationalrat 2019 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--26be4594e13ce1180ec8.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--26be4594e13ce1180ec8.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--26be4594e13ce1180ec8.Rmd)
- Parteiresultate Erneuerungswahl Nationalrat 2015 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--ab420e29426ee0ada873.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--ab420e29426ee0ada873.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--ab420e29426ee0ada873.Rmd)
- Listenresultate Erneuerungswahl Nationalrat 2015 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--4ec771177a2f053c632c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--4ec771177a2f053c632c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--4ec771177a2f053c632c.Rmd)
- Parteiresultate Erneuerungswahl Nationalrat 2011 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--2845ddaa3d8dcc7313b2.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--2845ddaa3d8dcc7313b2.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--2845ddaa3d8dcc7313b2.Rmd)
- Listenresultate Erneuerungswahl Nationalrat 2011 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--17e643e5b31eda6b0104.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--17e643e5b31eda6b0104.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--17e643e5b31eda6b0104.Rmd)
- Parteiresultate Erneuerungswahl Nationalrat 2007 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--e12bdc00d2a0c9692c45.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--e12bdc00d2a0c9692c45.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--e12bdc00d2a0c9692c45.Rmd)
- Listenresultate Erneuerungswahl Nationalrat 2007 (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--6aefbd7a01b8e7008653.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/693%40statistisches-amt-kanton-zuerich--6aefbd7a01b8e7008653.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/693%40statistisches-amt-kanton-zuerich--6aefbd7a01b8e7008653.Rmd)
