# Choose a resource for 694@statistisches-amt-kanton-zuerich

- Resultate 1. Wahlgang Gesamterneuerungswahl Regierungsrat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--f4f9f19777e7677887d8.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--f4f9f19777e7677887d8.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--f4f9f19777e7677887d8.Rmd)
- Resultate 1. Wahlgang Gesamterneuerungswahl Regierungsrat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--592af4c7dcc7c388eaa3.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--592af4c7dcc7c388eaa3.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--592af4c7dcc7c388eaa3.Rmd)
- Resultate 1. Wahlgang Gesamterneuerungswahl Regierungsrat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--ff029b97fd2b7da37a53.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--ff029b97fd2b7da37a53.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--ff029b97fd2b7da37a53.Rmd)
- Resultate 1. Wahlgang Gesamterneuerungswahl Regierungsrat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--31e8e6b09cc3d01103d7.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--31e8e6b09cc3d01103d7.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--31e8e6b09cc3d01103d7.Rmd)
- Resultate 1. Wahlgang Ersatzwahl Regierungsrat 2009 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--55d93b8f7f51197c1043.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--55d93b8f7f51197c1043.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--55d93b8f7f51197c1043.Rmd)
- Kandidierende 1. Wahlgang Gesamterneuerungswahl Regierungsrat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--6e196ef7aaaf33a51dcc.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--6e196ef7aaaf33a51dcc.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--6e196ef7aaaf33a51dcc.Rmd)
- Kandidierende 1. Wahlgang Ersatzwahl Regierungsrat 2009 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--736d56765f610c17e371.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--736d56765f610c17e371.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--736d56765f610c17e371.Rmd)
- Kandidierende 1. Wahlgang Gesamterneuerungswahl Regierungsrat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--0d93c2b85f76270b595e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--0d93c2b85f76270b595e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--0d93c2b85f76270b595e.Rmd)
- Kandidierende 1. Wahlgang Gesamterneuerungswahl Regierungsrat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--e08b0e678ea9c7d63ea7.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--e08b0e678ea9c7d63ea7.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--e08b0e678ea9c7d63ea7.Rmd)
- Kandidierende 1. Wahlgang Gesamterneuerungswahl Regierungsrat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--ff70ea86837c378fac40.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--ff70ea86837c378fac40.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--ff70ea86837c378fac40.Rmd)
- Resultate 1. Wahlgang Gesamterneuerungswahl Regierungsrat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--6fa49736e12cf3401575.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--6fa49736e12cf3401575.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--6fa49736e12cf3401575.Rmd)
- Kandidierende 1. Wahlgang Gesamterneuerungswahl Regierungsrat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--2407412c39a3f9eb6080.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/694%40statistisches-amt-kanton-zuerich--2407412c39a3f9eb6080.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/694%40statistisches-amt-kanton-zuerich--2407412c39a3f9eb6080.Rmd)
