# Choose a resource for 695@statistisches-amt-kanton-zuerich

- Resultate 1. Wahlgang Erneuerungswahl Ständerat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--bc3b9bb526baf6831d34.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--bc3b9bb526baf6831d34.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--bc3b9bb526baf6831d34.Rmd)
- Resultate 2. Wahlgang Erneuerungswahl Ständerat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--f04e9d5ca6750966e9d8.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--f04e9d5ca6750966e9d8.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--f04e9d5ca6750966e9d8.Rmd)
- Resultate 1. Wahlgang Erneuerungswahl Ständerat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--baa0a0a922e20583eaa3.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--baa0a0a922e20583eaa3.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--baa0a0a922e20583eaa3.Rmd)
- Resultate 2. Wahlgang Erneuerungswahl Ständerat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--d0b8b92baa74ebf14e5e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--d0b8b92baa74ebf14e5e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--d0b8b92baa74ebf14e5e.Rmd)
- Resultate 1. Wahlgang Erneuerungswahl Ständerat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--0cbfd3fbc365aeb505d2.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--0cbfd3fbc365aeb505d2.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--0cbfd3fbc365aeb505d2.Rmd)
- Resultate 2. Wahlgang Erneuerungswahl Ständerat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--b279e138f32819a9f6a0.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--b279e138f32819a9f6a0.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--b279e138f32819a9f6a0.Rmd)
- Resultate 1. Wahlgang Erneuerungswahl Ständerat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--72322bae5cb04b93e473.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--72322bae5cb04b93e473.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--72322bae5cb04b93e473.Rmd)
- Resultate 2. Wahlgang Erneuerungswahl Ständerat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--c35415df37455ebb6b97.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--c35415df37455ebb6b97.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--c35415df37455ebb6b97.Rmd)
- Kandidierende 1. Wahlgang Erneuerungswahl Ständerat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--a65bd9675b2d4700c6ab.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--a65bd9675b2d4700c6ab.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--a65bd9675b2d4700c6ab.Rmd)
- Kandidierende 2. Wahlgang Erneuerungswahl Ständerat 2007 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--9a55b492cce73e739650.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--9a55b492cce73e739650.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--9a55b492cce73e739650.Rmd)
- Kandidierende 1. Wahlgang Erneuerungswahl Ständerat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--75ac587d791fddb61158.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--75ac587d791fddb61158.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--75ac587d791fddb61158.Rmd)
- Kandidierende 2. Wahlgang Erneuerungswahl Ständerat 2011 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--37dbc19c1d593773dd9a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--37dbc19c1d593773dd9a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--37dbc19c1d593773dd9a.Rmd)
- Kandidierende 1. Wahlgang Erneuerungswahl Ständerat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--82a61af0e483a43311ba.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--82a61af0e483a43311ba.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--82a61af0e483a43311ba.Rmd)
- Kandidierende 2. Wahlgang Erneuerungswahl Ständerat 2015 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--282bda9da7d5d52fb6cd.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--282bda9da7d5d52fb6cd.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--282bda9da7d5d52fb6cd.Rmd)
- Kandidierende 1. Wahlgang Erneuerungswahl Ständerat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--c8aebc183b291b3d80e4.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--c8aebc183b291b3d80e4.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--c8aebc183b291b3d80e4.Rmd)
- Kandidierende 2. Wahlgang Erneuerungswahl Ständerat 2019 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--0cf38bd7bf26963c0551.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--0cf38bd7bf26963c0551.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--0cf38bd7bf26963c0551.Rmd)
- Kandidierende 1. Wahlgang Erneuerungswahl Ständerat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--ce1c05c98b93230b084c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--ce1c05c98b93230b084c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--ce1c05c98b93230b084c.Rmd)
- Resultate 1. Wahlgang Erneuerungswahl Ständerat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--4dddf911218db4172221.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--4dddf911218db4172221.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--4dddf911218db4172221.Rmd)
- Resultate 2. Wahlgang Erneuerungswahl Ständerat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--a07fe38da5981f80d322.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--a07fe38da5981f80d322.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--a07fe38da5981f80d322.Rmd)
- Kandidierende 2. Wahlgang Erneuerungswahl Ständerat 2023 (csv): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--c6ca52599f5763151746.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/695%40statistisches-amt-kanton-zuerich--c6ca52599f5763151746.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/695%40statistisches-amt-kanton-zuerich--c6ca52599f5763151746.Rmd)
