# Choose a resource for 715@fachstelle-ogd-kanton-zuerich

- ZH Datasets Visits - 2019 November (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--a729ed57da9fc313f80d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--a729ed57da9fc313f80d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--a729ed57da9fc313f80d.Rmd)
- ZH Datasets Visits - 2019 Dezember (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--57950b08dc9081dbb120.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--57950b08dc9081dbb120.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--57950b08dc9081dbb120.Rmd)
- ZH Datasets Visits - 2020 Januar (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--f0a462b62ae2587d2636.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--f0a462b62ae2587d2636.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--f0a462b62ae2587d2636.Rmd)
- ZH Datasets Visits - 2020 Februar (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--7a9ac77bd0bb20949dbe.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--7a9ac77bd0bb20949dbe.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--7a9ac77bd0bb20949dbe.Rmd)
- ZH Datasets Visits - 2020 März (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--50932d7614749544b5a9.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--50932d7614749544b5a9.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--50932d7614749544b5a9.Rmd)
- ZH Datasets Visits - 2020 April (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--c7d2f1a24c11d96d3b0e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--c7d2f1a24c11d96d3b0e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--c7d2f1a24c11d96d3b0e.Rmd)
- ZH Datasets Visits - 2020 Mai (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--f461cf3f9b6de2baa408.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--f461cf3f9b6de2baa408.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--f461cf3f9b6de2baa408.Rmd)
- ZH Datasets Visits - 2020 Juni (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--f57de0159f8f0f1b223e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--f57de0159f8f0f1b223e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--f57de0159f8f0f1b223e.Rmd)
- ZH Datasets Visits - 2020 Juli (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--808f153bfe055a4a60ce.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--808f153bfe055a4a60ce.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--808f153bfe055a4a60ce.Rmd)
- ZH Datasets Visits - 2020 August (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--15faf12acced633813cd.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--15faf12acced633813cd.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--15faf12acced633813cd.Rmd)
- ZH Datasets Visits - 2020 September (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--6eecbd8bbf677496bfd0.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--6eecbd8bbf677496bfd0.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--6eecbd8bbf677496bfd0.Rmd)
- ZH Datasets Visits - 2020 Oktober (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--54f17951a9467e747f40.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--54f17951a9467e747f40.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--54f17951a9467e747f40.Rmd)
- ZH Datasets Visits - 2020 November (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--a1c4ea82ba1bfea6f207.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--a1c4ea82ba1bfea6f207.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--a1c4ea82ba1bfea6f207.Rmd)
- ZH Datasets Visits - 2020 Dezember (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--64552b400a5a4bd87d2e.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--64552b400a5a4bd87d2e.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--64552b400a5a4bd87d2e.Rmd)
- ZH Datasets Visits - 2021 Januar (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--7eb26867fe06f0ae2c72.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--7eb26867fe06f0ae2c72.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--7eb26867fe06f0ae2c72.Rmd)
- ZH Datasets Visits - 2021 Februar (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--402f955c21efcd27e366.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--402f955c21efcd27e366.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--402f955c21efcd27e366.Rmd)
- ZH Datasets Visits - 2018 Februar (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--92d81c183a9370aba61f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--92d81c183a9370aba61f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--92d81c183a9370aba61f.Rmd)
- ZH Datasets Visits - 2018 März (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--21686104cba08c94387b.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--21686104cba08c94387b.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--21686104cba08c94387b.Rmd)
- ZH Datasets Visits - 2018 April (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--c476b913ba83bbb5b264.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--c476b913ba83bbb5b264.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--c476b913ba83bbb5b264.Rmd)
- ZH Datasets Visits - 2018 Mai (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--b46fbf7d66ede65d196f.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--b46fbf7d66ede65d196f.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--b46fbf7d66ede65d196f.Rmd)
- ZH Datasets Visits - 2018 Juni (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--8ed99935487da2415a98.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--8ed99935487da2415a98.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--8ed99935487da2415a98.Rmd)
- ZH Datasets Visits - 2018 Juli (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--29fd3b4061093a037a4d.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--29fd3b4061093a037a4d.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--29fd3b4061093a037a4d.Rmd)
- ZH Datasets Visits - 2018 August (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--33a377499dc6a4ee7513.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--33a377499dc6a4ee7513.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--33a377499dc6a4ee7513.Rmd)
- ZH Datasets Visits - 2018 September (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--e85606e5d3ed7f81d7c2.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--e85606e5d3ed7f81d7c2.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--e85606e5d3ed7f81d7c2.Rmd)
- ZH Datasets Visits - 2018 Oktober (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--8501c5d6195a566e8e61.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--8501c5d6195a566e8e61.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--8501c5d6195a566e8e61.Rmd)
- ZH Datasets Visits - 2018 November (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--1f0f47043ef937032f5a.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--1f0f47043ef937032f5a.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--1f0f47043ef937032f5a.Rmd)
- ZH Datasets Visits - 2018 Dezember (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--bb4b29c86b74535746aa.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--bb4b29c86b74535746aa.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--bb4b29c86b74535746aa.Rmd)
- ZH Datasets Visits - 2019 Januar (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--6a23f58786b449469c58.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--6a23f58786b449469c58.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--6a23f58786b449469c58.Rmd)
- ZH Datasets Visits - 2019 Februar (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--c955d273439f0ed621be.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--c955d273439f0ed621be.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--c955d273439f0ed621be.Rmd)
- ZH Datasets Visits - 2019 März (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--c1135c58b7d7cbd31f20.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--c1135c58b7d7cbd31f20.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--c1135c58b7d7cbd31f20.Rmd)
- ZH Datasets Visits - 2019 April (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--7cd9b8b09e9a033fdcbc.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--7cd9b8b09e9a033fdcbc.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--7cd9b8b09e9a033fdcbc.Rmd)
- ZH Datasets Visits - 2019 Mai (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--21775a543c6ab5f447ad.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--21775a543c6ab5f447ad.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--21775a543c6ab5f447ad.Rmd)
- ZH Datasets Visits - 2019 Juni (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--fb96b76d6a0bd6712941.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--fb96b76d6a0bd6712941.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--fb96b76d6a0bd6712941.Rmd)
- ZH Datasets Visits - 2019 Juli (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--7991078d569e011b2d20.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--7991078d569e011b2d20.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--7991078d569e011b2d20.Rmd)
- ZH Datasets Visits - 2019 August (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--d127d86b26f7ca6980ae.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--d127d86b26f7ca6980ae.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--d127d86b26f7ca6980ae.Rmd)
- ZH Datasets Visits - 2019 September (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--a4e3128d17031c73815c.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--a4e3128d17031c73815c.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--a4e3128d17031c73815c.Rmd)
- ZH Datasets Visits - 2019 Oktober (CSV): [Python](https://github.com/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--9a31d178eed54475d8c6.ipynb) · [Colab](https://colab.research.google.com/github/openZH/starter-code-openZH/blob/main/02_python/715%40fachstelle-ogd-kanton-zuerich--9a31d178eed54475d8c6.ipynb) · [R Markdown](https://github.com/openZH/starter-code-openZH/blob/main/01_r-markdown/715%40fachstelle-ogd-kanton-zuerich--9a31d178eed54475d8c6.Rmd)
